In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
from scipy.sparse import csr_matrix

In [3]:
excel = "C:\\Users\\brian\\Documents\\Data Sabic\\2019-10-24 SAP Work Order & Notification Report.xlsx"

In [4]:
df = pd.read_excel(excel,sheet_name='INFO')

In [5]:
df['Notification'] = pd.to_numeric(df['Notification'], errors='coerce').fillna(0).astype(np.int64)

In [6]:
df.head()

Maintenance Plan           Equipment Manual/ Auto      Order  Notification  \
0     BL1000001170  BL000000005-10-035         AUTO  913195093     713335025   
1      Not Planned  BL000000101-12-206       MANUAL  913195171     713335093   
2      Not Planned  BL000000104-09-851       MANUAL  913195174     713335096   
3      Not Planned  BL000000154-12-730       MANUAL  913195175     713335097   
4     BL1000001170  BL000000101-12-206         AUTO  913195180     713335112   

                                        Header text: Created on  \
0  * 09/19/2016 19:04:48 rick kessler (FNP_050408... 2016-09-19   
1  * 09/19/2016 19:13:49 rick kessler (FNP_050408... 2016-09-19   
2  * 09/19/2016 19:14:44 rick kessler (FNP_050408... 2016-09-19   
3  * 09/19/2016 19:14:57 rick kessler (FNP_050408... 2016-09-19   
4  * 09/19/2016 19:16:05 rick kessler (FNP_050408... 2016-09-19   

                Sort field Description of Technical Object  \
0  005-10-035 FRCD DRFT FA                FORCED DRAFT FAN   
1  101-12-206 LN 2 PLLTIZE               LINE 2 PELLETIZER   
2      104-09-851 FC1 POLY   PUMP, FLASH CHAMBER 1 POLYMER   
3   154-12-730 BD EXTRUDER                     BD EXTRUDER   
4  101-12-206 LN 2 PLLTIZE               LINE 2 PELLETIZER   

                                Description  ... ABC indicator User Status  \
0   15-002600-000, Remove valve and free up  ...             E        COMP   
1  16-001987-000, 101-12-206 LINE 2 PELLETI  ...             E        COMP   
2  16-002676-000, 104-09-851 FC1 POLY, Insp  ...             E        COMP   
3  16-002683-000, 154-12-730 BD EXTRUDER, I  ...             E        COMP   
4  16-002984-000, 101-12-206 LINE 2 PELLETI  ...             E        COMP   

                        System status Priority Estimated costs  \
0       CLSD DLFL NCMP NMAT PRC  SKKP        4             NaN   
1       CLSD ESTC NCMP NMAT PRC  SKKP        3             NaN   
2             CLSD DLFL NCMP NMAT PRC        4             NaN   
3  CLSD ESTC MSCP NMAT PRC  SETC SKKP        3             NaN   
4  CLSD ESTC MSCP NMAT PRC  SETC SKKP        3             NaN   

   Total planned costs  Total actual costs  Basic start date  \
0                  NaN                 NaN               NaT   
1                  NaN                 NaN               NaT   
2                  NaN                 NaN               NaT   
3                  NaN                 NaN               NaT   
4                  NaN                 NaN               NaT   

   Basic finish date MaintActivityType  
0                NaT               NaN  
1                NaT               NaN  
2                NaT               NaN  
3                NaT               NaN  
4                NaT               NaN  

[5 rows x 22 columns]

In [7]:
df['Tech ID'] = df['Sort field'].apply(lambda x: x.split()[0])

In [8]:
df.head()

Maintenance Plan           Equipment Manual/ Auto      Order  Notification  \
0     BL1000001170  BL000000005-10-035         AUTO  913195093     713335025   
1      Not Planned  BL000000101-12-206       MANUAL  913195171     713335093   
2      Not Planned  BL000000104-09-851       MANUAL  913195174     713335096   
3      Not Planned  BL000000154-12-730       MANUAL  913195175     713335097   
4     BL1000001170  BL000000101-12-206         AUTO  913195180     713335112   

                                        Header text: Created on  \
0  * 09/19/2016 19:04:48 rick kessler (FNP_050408... 2016-09-19   
1  * 09/19/2016 19:13:49 rick kessler (FNP_050408... 2016-09-19   
2  * 09/19/2016 19:14:44 rick kessler (FNP_050408... 2016-09-19   
3  * 09/19/2016 19:14:57 rick kessler (FNP_050408... 2016-09-19   
4  * 09/19/2016 19:16:05 rick kessler (FNP_050408... 2016-09-19   

                Sort field Description of Technical Object  \
0  005-10-035 FRCD DRFT FA                FORCED DRAFT FAN   
1  101-12-206 LN 2 PLLTIZE               LINE 2 PELLETIZER   
2      104-09-851 FC1 POLY   PUMP, FLASH CHAMBER 1 POLYMER   
3   154-12-730 BD EXTRUDER                     BD EXTRUDER   
4  101-12-206 LN 2 PLLTIZE               LINE 2 PELLETIZER   

                                Description  ... User Status  \
0   15-002600-000, Remove valve and free up  ...        COMP   
1  16-001987-000, 101-12-206 LINE 2 PELLETI  ...        COMP   
2  16-002676-000, 104-09-851 FC1 POLY, Insp  ...        COMP   
3  16-002683-000, 154-12-730 BD EXTRUDER, I  ...        COMP   
4  16-002984-000, 101-12-206 LINE 2 PELLETI  ...        COMP   

                        System status Priority Estimated costs  \
0       CLSD DLFL NCMP NMAT PRC  SKKP        4             NaN   
1       CLSD ESTC NCMP NMAT PRC  SKKP        3             NaN   
2             CLSD DLFL NCMP NMAT PRC        4             NaN   
3  CLSD ESTC MSCP NMAT PRC  SETC SKKP        3             NaN   
4  CLSD ESTC MSCP NMAT PRC  SETC SKKP        3             NaN   

  Total planned costs  Total actual costs  Basic start date  \
0                 NaN                 NaN               NaT   
1                 NaN                 NaN               NaT   
2                 NaN                 NaN               NaT   
3                 NaN                 NaN               NaT   
4                 NaN                 NaN               NaT   

   Basic finish date  MaintActivityType     Tech ID  
0                NaT                NaN  005-10-035  
1                NaT                NaN  101-12-206  
2                NaT                NaN  104-09-851  
3                NaT                NaN  154-12-730  
4                NaT                NaN  101-12-206  

[5 rows x 23 columns]

In [9]:
df2 = pd.read_excel(excel,sheet_name='CYCLE')

In [10]:
df2

Maint plan  cycle
0   500000770376     52
1   500000770393     52
2   500000770396     52
3   500000770397     52
4   500000770404     52
5   500000842187      1
6   500000843147     52
7   500000916370     52
8   BL1000001159      4
9   BL1000001170      1
10  BL1000001205      1
11  BL1000001271      4
12  BL1000001608      4
13  BL1000001611      4
14  BL1000001612     52
15  BL1000001614     52

In [11]:
d = dict(zip(df2['Maint plan'], df2['cycle']))

In [12]:
df['Cycle'] = df['Maintenance Plan'].map(d)

In [13]:
df.head()

Maintenance Plan           Equipment Manual/ Auto      Order  Notification  \
0     BL1000001170  BL000000005-10-035         AUTO  913195093     713335025   
1      Not Planned  BL000000101-12-206       MANUAL  913195171     713335093   
2      Not Planned  BL000000104-09-851       MANUAL  913195174     713335096   
3      Not Planned  BL000000154-12-730       MANUAL  913195175     713335097   
4     BL1000001170  BL000000101-12-206         AUTO  913195180     713335112   

                                        Header text: Created on  \
0  * 09/19/2016 19:04:48 rick kessler (FNP_050408... 2016-09-19   
1  * 09/19/2016 19:13:49 rick kessler (FNP_050408... 2016-09-19   
2  * 09/19/2016 19:14:44 rick kessler (FNP_050408... 2016-09-19   
3  * 09/19/2016 19:14:57 rick kessler (FNP_050408... 2016-09-19   
4  * 09/19/2016 19:16:05 rick kessler (FNP_050408... 2016-09-19   

                Sort field Description of Technical Object  \
0  005-10-035 FRCD DRFT FA                FORCED DRAFT FAN   
1  101-12-206 LN 2 PLLTIZE               LINE 2 PELLETIZER   
2      104-09-851 FC1 POLY   PUMP, FLASH CHAMBER 1 POLYMER   
3   154-12-730 BD EXTRUDER                     BD EXTRUDER   
4  101-12-206 LN 2 PLLTIZE               LINE 2 PELLETIZER   

                                Description  ...  \
0   15-002600-000, Remove valve and free up  ...   
1  16-001987-000, 101-12-206 LINE 2 PELLETI  ...   
2  16-002676-000, 104-09-851 FC1 POLY, Insp  ...   
3  16-002683-000, 154-12-730 BD EXTRUDER, I  ...   
4  16-002984-000, 101-12-206 LINE 2 PELLETI  ...   

                        System status Priority Estimated costs  \
0       CLSD DLFL NCMP NMAT PRC  SKKP        4             NaN   
1       CLSD ESTC NCMP NMAT PRC  SKKP        3             NaN   
2             CLSD DLFL NCMP NMAT PRC        4             NaN   
3  CLSD ESTC MSCP NMAT PRC  SETC SKKP        3             NaN   
4  CLSD ESTC MSCP NMAT PRC  SETC SKKP        3             NaN   

  Total planned costs Total actual costs  Basic start date  Basic finish date  \
0                 NaN                NaN               NaT                NaT   
1                 NaN                NaN               NaT                NaT   
2                 NaN                NaN               NaT                NaT   
3                 NaN                NaN               NaT                NaT   
4                 NaN                NaN               NaT                NaT   

   MaintActivityType     Tech ID Cycle  
0                NaN  005-10-035   1.0  
1                NaN  101-12-206   NaN  
2                NaN  104-09-851   NaN  
3                NaN  154-12-730   NaN  
4                NaN  101-12-206   1.0  

[5 rows x 24 columns]

In [69]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1713 entries, 0 to 1712
Data columns (total 25 columns):
Maintenance Plan                   1713 non-null object
Equipment                          1713 non-null object
Manual/ Auto                       1713 non-null object
Order                              1713 non-null int64
Notification                       1713 non-null int64
Header text:                       1713 non-null object
Created on                         1713 non-null datetime64[ns]
Sort field                         1713 non-null object
Description of Technical Object    1713 non-null object
Description                        1713 non-null object
Functional Location                1713 non-null object
Main work center                   1713 non-null object
ABC indicator                      1713 non-null object
User Status                        1713 non-null object
System status                      1713 non-null object
Priority                           1713 non-nul

In [15]:
df['Cycle'].fillna(value='Not Planned',inplace=True)

In [65]:
df.head()

Maintenance Plan           Equipment Manual/ Auto      Order  Notification  \
0     BL1000001170  BL000000005-10-035         AUTO  913195093     713335025   
1      Not Planned  BL000000101-12-206       MANUAL  913195171     713335093   
2      Not Planned  BL000000104-09-851       MANUAL  913195174     713335096   
3      Not Planned  BL000000154-12-730       MANUAL  913195175     713335097   
4     BL1000001170  BL000000101-12-206         AUTO  913195180     713335112   

                                        Header text: Created on  \
0  * 09/19/2016 19:04:48 rick kessler (FNP_050408... 2016-09-19   
1  * 09/19/2016 19:13:49 rick kessler (FNP_050408... 2016-09-19   
2  * 09/19/2016 19:14:44 rick kessler (FNP_050408... 2016-09-19   
3  * 09/19/2016 19:14:57 rick kessler (FNP_050408... 2016-09-19   
4  * 09/19/2016 19:16:05 rick kessler (FNP_050408... 2016-09-19   

                Sort field Description of Technical Object  \
0  005-10-035 FRCD DRFT FA                FORCED DRAFT FAN   
1  101-12-206 LN 2 PLLTIZE               LINE 2 PELLETIZER   
2      104-09-851 FC1 POLY   PUMP, FLASH CHAMBER 1 POLYMER   
3   154-12-730 BD EXTRUDER                     BD EXTRUDER   
4  101-12-206 LN 2 PLLTIZE               LINE 2 PELLETIZER   

                                Description  ... Priority Estimated costs  \
0   15-002600-000, Remove valve and free up  ...        4             NaN   
1  16-001987-000, 101-12-206 LINE 2 PELLETI  ...        3             NaN   
2  16-002676-000, 104-09-851 FC1 POLY, Insp  ...        4             NaN   
3  16-002683-000, 154-12-730 BD EXTRUDER, I  ...        3             NaN   
4  16-002984-000, 101-12-206 LINE 2 PELLETI  ...        3             NaN   

  Total planned costs Total actual costs Basic start date  Basic finish date  \
0                 NaN                NaN              NaT                NaT   
1                 NaN                NaN              NaT                NaT   
2                 NaN                NaN              NaT                NaT   
3                 NaN                NaN              NaT                NaT   
4                 NaN                NaN              NaT                NaT   

   MaintActivityType     Tech ID        Cycle Text Length  
0                NaN  005-10-035            1          20  
1                NaN  101-12-206  Not Planned          12  
2                NaN  104-09-851  Not Planned          43  
3                NaN  154-12-730  Not Planned          20  
4                NaN  101-12-206            1          69  

[5 rows x 25 columns]

In [67]:
df['Header text:'] = df['Header text:'].astype('str') 

In [84]:
equip = df.groupby('Equipment').count()

In [86]:
equip.sort_values(by='Order',ascending=False)

Maintenance Plan  Manual/ Auto  Order  Notification  \
Equipment                                                                 
BL000000155-12-600               235           235    235           235   
BL000000005-10-001               194           194    194           194   
BL000000005-10-306               187           187    187           187   
BL000000101-12-206               130           130    130           130   
BL000000154-12-730               127           127    127           127   
BL000000157-12-034                95            95     95            95   
BL000000152-12-711                77            77     77            77   
BL000000101-12-002                70            70     70            70   
BL000000101-29-200                52            52     52            52   
BL000000005-10-084                50            50     50            50   
BL000000104-09-859                32            32     32            32   
BL000000104-09-851                29            29     29            29   
BL000000101-09-003                29            29     29            29   
BL000000101-09-333                26            26     26            26   
BL000000104-09-850                25            25     25            25   
BL000000101-09-004                25            25     25            25   
BL000000101-09-335                23            23     23            23   
BL000000101-09-334                22            22     22            22   
BL000000101-19-011                21            21     21            21   
BL000000104-09-869                20            20     20            20   
BL000000101-12-067                19            19     19            19   
BL000000105-09-969                19            19     19            19   
BL000000101-29-202                17            17     17            17   
BL000000005-10-002                17            17     17            17   
BL00000101-09-003M                16            16     16            16   
BL000000007-09-780                15            15     15            15   
BL000000104-10-439                13            13     13            13   
BL000000007-09-781                12            12     12            12   
BL000000101-29-203                11            11     11            11   
BL000000101-29-201                11            11     11            11   
BL000000104-10-441                10            10     10            10   
BL000000104-10-442                10            10     10            10   
BL000000104-09-862                 9             9      9             9   
BL000000101-29-004                 9             9      9             9   
BL000000104-12-455                 7             7      7             7   
BL000000101-08-206                 6             6      6             6   
BL00000104-09-859M                 5             5      5             5   
BL00000104-09-851M                 5             5      5             5   
BL000000104-10-443                 5             5      5             5   
BL000000104-09-860                 5             5      5             5   
BL00000104-09-850M                 4             4      4             4   
BL000000005-10-035                 3             3      3             3   
BL000155-PSL-15312                 3             3      3             3   
BL000000101-08-062                 3             3      3             3   
BL000000104-10-445                 2             2      2             2   
BL000000104-09-883                 2             2      2             2   
BL00000104-10-439M                 2             2      2             2   
BL000000151-12-702                 1             1      1             1   
BL000000104-09-884                 1             1      1             1   
BL000000101-08-063                 1             1      1             1   
BL000000101-09-338                 1             1      1             1   

                    Header text:  Created on

In [93]:
df[df["Equipment"] == 'BL000000155-12-600']

Maintenance Plan           Equipment Manual/ Auto      Order  \
9         Not Planned  BL000000155-12-600       MANUAL  913246200   
14        Not Planned  BL000000155-12-600       MANUAL  913269163   
45       500000916370  BL000000155-12-600         AUTO  913408357   
56        Not Planned  BL000000155-12-600       MANUAL  913439194   
65        Not Planned  BL000000155-12-600       MANUAL  913477654   
66        Not Planned  BL000000155-12-600       MANUAL  913482274   
181      500000916370  BL000000155-12-600         AUTO  913728979   
186       Not Planned  BL000000155-12-600       MANUAL  913742825   
194       Not Planned  BL000000155-12-600       MANUAL  913761517   
197      500000916370  BL000000155-12-600         AUTO  913769490   
198       Not Planned  BL000000155-12-600       MANUAL  913769494   
199       Not Planned  BL000000155-12-600       MANUAL  913769497   
200       Not Planned  BL000000155-12-600       MANUAL  913769498   
240       Not Planned  BL000000155-12-600       MANUAL  913905693   
309       Not Planned  BL000000155-12-600       MANUAL  914061969   
314       Not Planned  BL000000155-12-600       MANUAL  914075796   
321       Not Planned  BL000000155-12-600       MANUAL  914103649   
322       Not Planned  BL000000155-12-600       MANUAL  914110928   
330       Not Planned  BL000000155-12-600       MANUAL  914141192   
372       Not Planned  BL000000155-12-600       MANUAL  914249951   
384       Not Planned  BL000000155-12-600       MANUAL  914284124   
396       Not Planned  BL000000155-12-600       MANUAL  914315241   
398       Not Planned  BL000000155-12-600       MANUAL  914315351   
463       Not Planned  BL000000155-12-600       MANUAL  914481358   
466       Not Planned  BL000000155-12-600       MANUAL  914485822   
476       Not Planned  BL000000155-12-600       MANUAL  914500535   
508       Not Planned  BL000000155-12-600       MANUAL  920468172   
520       Not Planned  BL000000155-12-600       MANUAL  920503987   
541       Not Planned  BL000000155-12-600       MANUAL  920521538   
552       Not Planned  BL000000155-12-600       MANUAL  920538622   
...               ...                 ...          ...        ...   
1392      Not Planned  BL000000155-12-600       MANUAL  938502120   
1411      Not Planned  BL000000155-12-600       MANUAL  938546967   
1412      Not Planned  BL000000155-12-600       MANUAL  938547033   
1421      Not Planned  BL000000155-12-600       MANUAL  938600780   
1431     BL1000001612  BL000000155-12-600         AUTO  938623243   
1432      Not Planned  BL000000155-12-600       MANUAL  938646079   
1436     BL1000001608  BL000000155-12-600         AUTO  938646354   
1447      Not Planned  BL000000155-12-600       MANUAL  938692565   
1461      Not Planned  BL000000155-12-600       MANUAL  938740399   
1462      Not Planned  BL000000155-12-600       MANUAL  938740527   
1466      Not Planned  BL000000155-12-600       MANUAL  938786343   
1478      Not Planned  BL000000155-12-600       MANUAL  938829362   
1483      Not Planned  BL000000155-12-600       MANUAL  938829722   
1484      Not Planned  BL000000155-12-600       MANUAL  938829739   
1490      Not Planned  BL000000155-12-600       MANUAL  938868636   
1518      Not Planned  BL000000155-12-600       MANUAL  938916400   
1522      Not Planned  BL000000155-12-600       MANUAL  938916969   
1572     BL1000001608  BL000000155-12-600         AUTO  939004375   
1574     BL1000001611  BL000000155-12-600         AUTO  939004458   
1586      Not Planned  BL000000155-12-600       MANUAL  939066515   
1594      Not Planned  BL000000155-12-600       MANUAL  939089658   
1595      Not Planned  BL000000155-12-600       MANUAL  939112388   
1614      Not Planned  BL000000155-12-600       MANUAL  939178389   
1615      Not Planned  BL000000155-12-600       MANUAL  939200136   
1636      Not Planned  BL000000155-12-600       MANUAL  939265068   
1637      Not Planned  BL000000155-12-600       MANUAL  939289599   
165

In [95]:
df["Equipment"].value_counts()

BL000000155-12-600    235
BL000000005-10-001    194
BL000000005-10-306    187
BL000000101-12-206    130
BL000000154-12-730    127
BL000000157-12-034     95
BL000000152-12-711     77
BL000000101-12-002     70
BL000000101-29-200     52
BL000000005-10-084     50
BL000000104-09-859     32
BL000000104-09-851     29
BL000000101-09-003     29
BL000000101-09-333     26
BL000000101-09-004     25
BL000000104-09-850     25
BL000000101-09-335     23
BL000000101-09-334     22
BL000000101-19-011     21
BL000000104-09-869     20
BL000000101-12-067     19
BL000000105-09-969     19
BL000000101-29-202     17
BL000000005-10-002     17
BL00000101-09-003M     16
BL000000007-09-780     15
BL000000104-10-439     13
BL000000007-09-781     12
BL000000101-29-201     11
BL000000101-29-203     11
BL000000104-10-441     10
BL000000104-10-442     10
BL000000104-09-862      9
BL000000101-29-004      9
BL000000104-12-455      7
BL000000101-08-206      6
BL00000104-09-859M      5
BL000000104-09-860      5
BL000000104-

In [18]:
import string

In [19]:
import nltk

In [20]:
nltk.download('stopwords')

[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\brian\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


True

In [21]:
from nltk.corpus import stopwords
stopwords.words('english')[0:10]

['i', 'me', 'my', 'myself', 'we', 'our', 'ours', 'ourselves', 'you', "you're"]

In [22]:
def text_clean(text):
    
    nopunc = [char for char in text if char not in string.punctuation]
    
    nopunc = ''.join(nopunc)
    
    return [word for word in nopunc.split() if word.lower() not in stopwords.words('english')]

In [23]:
df['Header text:'].head(5)

0    * 09/19/2016 19:04:48 rick kessler (FNP_050408...
1    * 09/19/2016 19:13:49 rick kessler (FNP_050408...
2    * 09/19/2016 19:14:44 rick kessler (FNP_050408...
3    * 09/19/2016 19:14:57 rick kessler (FNP_050408...
4    * 09/19/2016 19:16:05 rick kessler (FNP_050408...
Name: Header text:, dtype: object

In [24]:
df['Text Length'] = df['Header text:'].apply(text_clean).apply(len)

In [25]:
from sklearn.feature_extraction.text import CountVectorizer

In [26]:
bowxform = CountVectorizer(analyzer=text_clean).fit(df['Header text:'])

In [27]:
print(len(bowxform.vocabulary_))

10126


In [28]:
mess3 = df['Header text:'][2]
print(mess3)

* 09/19/2016 19:14:44 rick kessler (FNP_050408_F) * 104-09-851 FC1 POLY, Inspect Piping for CUI: OIL LOOP WHERE FLASH FIRE   STARTED, Insulation was removed and replaced. When insulation was   removed, the pipe was inspected and spots of corrosion were noted.Remove   insulation during turnaround, inspect, repair if necessary, coat and   replace insulation. * 11-10-2016 18:31:53 Jim Bowers (US_501692235) *  GLOBAL COMPLETED THIS JOB 11-2-2016.


In [29]:
bow3 = bowxform.transform([mess3])
print(bow3)

  (0, 1521)	1
  (0, 1709)	1
  (0, 1804)	1
  (0, 1840)	1
  (0, 3001)	1
  (0, 3125)	1
  (0, 5198)	1
  (0, 5295)	1
  (0, 5337)	1
  (0, 5625)	1
  (0, 5645)	1
  (0, 5651)	1
  (0, 5667)	1
  (0, 5742)	1
  (0, 5898)	1
  (0, 5908)	1
  (0, 5924)	1
  (0, 5941)	1
  (0, 6026)	1
  (0, 6234)	1
  (0, 6342)	1
  (0, 6434)	1
  (0, 6762)	1
  (0, 7063)	1
  (0, 7638)	1
  (0, 7754)	1
  (0, 8402)	1
  (0, 8403)	1
  (0, 8425)	3
  (0, 8488)	1
  (0, 8777)	1
  (0, 8806)	1
  (0, 8977)	1
  (0, 9257)	2
  (0, 9263)	1
  (0, 9277)	1
  (0, 9278)	1
  (0, 9345)	1
  (0, 9622)	1
  (0, 9909)	1


In [30]:
print(bowxform.get_feature_names()[9909])

turnaround


In [31]:
bow = bowxform.transform(df['Header text:'])

In [32]:
print(bow.shape)
print(bow.nnz) # amount of non-zeros

(1713, 10126)
42494


In [33]:
sparsity = (100.0 * bow.nnz / (bow.shape[0] * bow.shape[1]))
print('sparsity: {}'.format(round(sparsity)))

sparsity: 0


In [34]:
from sklearn.feature_extraction.text import TfidfTransformer

In [35]:
tfidfx = TfidfTransformer().fit(bow)

In [36]:
tfidf3 = tfidfx.transform(bow3)
print(tfidf3)

  (0, 9909)	0.1499075033480169
  (0, 9622)	0.15766665348626746
  (0, 9345)	0.11559200259137001
  (0, 9278)	0.08812751920942793
  (0, 9277)	0.09851815623905447
  (0, 9263)	0.09960782185813376
  (0, 9257)	0.19775137481021704
  (0, 8977)	0.12688113068795687
  (0, 8806)	0.17879659107128973
  (0, 8777)	0.15766665348626746
  (0, 8488)	0.11559200259137001
  (0, 8425)	0.41243424981337334
  (0, 8403)	0.11346184627635698
  (0, 8402)	0.12457317628108784
  (0, 7754)	0.16944644473759693
  (0, 7638)	0.16944644473759693
  (0, 7063)	0.10154680362102783
  (0, 6762)	0.14682822960481726
  (0, 6434)	0.1534622640043607
  (0, 6342)	0.13563227455731297
  (0, 6234)	0.1080463752589778
  (0, 6026)	0.17879659107128973
  (0, 5941)	0.08680942913726636
  (0, 5924)	0.14682822960481726
  (0, 5908)	0.1441121176706679
  (0, 5898)	0.1499075033480169
  (0, 5742)	0.17879659107128973
  (0, 5667)	0.11559200259137001
  (0, 5651)	0.16944644473759693
  (0, 5645)	0.17879659107128973
  (0, 5625)	0.1534622640043607
  (0, 5337)	0.

In [37]:
print(bowxform.get_feature_names()[9909])

turnaround


In [38]:
print(tfidfx.idf_[bowxform.vocabulary_['fix']])

7.060290738037835


In [39]:
tfidf = tfidfx.transform(bow)
print(tfidf.shape)

(1713, 10126)


In [40]:
tfidf3.sum()

5.9782394048429985

In [41]:
print(tfidf)

  (0, 10086)	0.16093646403504225
  (0, 9965)	0.6192517192130789
  (0, 9715)	0.21263168468446075
  (0, 9492)	0.17232928705074455
  (0, 9345)	0.16395791870399865
  (0, 9277)	0.13974004679729188
  (0, 9126)	0.2309362528528563
  (0, 8784)	0.11417979962069731
  (0, 8488)	0.16395791870399865
  (0, 8173)	0.22363741240834734
  (0, 8172)	0.2082639836088106
  (0, 7959)	0.24034609478288166
  (0, 7528)	0.253608522096902
  (0, 6615)	0.2044113982248156
  (0, 5667)	0.16395791870399865
  (0, 3098)	0.253608522096902
  (0, 1521)	0.16613933823695828
  (1, 9345)	0.24428015866046454
  (1, 8488)	0.24428015866046454
  (1, 6534)	0.2735578180754783
  (1, 6302)	0.279657424120428
  (1, 6002)	0.202541487764333
  (1, 5814)	0.3778501856157452
  (1, 5667)	0.24428015866046454
  (1, 5454)	0.3778501856157452
  :	:
  (1712, 6315)	0.07069495239235246
  (1712, 6182)	0.07069495239235246
  (1712, 5953)	0.07069495239235246
  (1712, 5940)	0.048831219951068455
  (1712, 5824)	0.07069495239235246
  (1712, 5717)	0.070694952392352

In [42]:
test = pd.DataFrame(tfidf)

In [43]:
test.head()

0
0    (0, 10086)\t0.16093646403504225\n  (0, 9965)...
1    (0, 9345)\t0.24428015866046454\n  (0, 8488)\...
2    (0, 9909)\t0.1499075033480169\n  (0, 9622)\t...
3    (0, 9845)\t0.17831278967496197\n  (0, 9811)\...
4    (0, 10100)\t0.11713431970231188\n  (0, 9345)...

In [44]:
test.shape

(1713, 1)

In [45]:
print(test.iloc[0,0])

  (0, 10086)	0.16093646403504225
  (0, 9965)	0.6192517192130789
  (0, 9715)	0.21263168468446075
  (0, 9492)	0.17232928705074455
  (0, 9345)	0.16395791870399865
  (0, 9277)	0.13974004679729188
  (0, 9126)	0.2309362528528563
  (0, 8784)	0.11417979962069731
  (0, 8488)	0.16395791870399865
  (0, 8173)	0.22363741240834734
  (0, 8172)	0.2082639836088106
  (0, 7959)	0.24034609478288166
  (0, 7528)	0.253608522096902
  (0, 6615)	0.2044113982248156
  (0, 5667)	0.16395791870399865
  (0, 3098)	0.253608522096902
  (0, 1521)	0.16613933823695828


In [46]:
arg = np.argwhere(tfidf)

In [47]:
arg

array([[    0, 10086],
       [    0,  9965],
       [    0,  9715],
       ...,
       [ 1712,  1417],
       [ 1712,  1404],
       [ 1712,    60]], dtype=int32)

In [48]:
argdf = pd.DataFrame(arg)

In [49]:
argdf

0      1
0         0  10086
1         0   9965
2         0   9715
3         0   9492
4         0   9345
5         0   9277
6         0   9126
7         0   8784
8         0   8488
9         0   8173
10        0   8172
11        0   7959
12        0   7528
13        0   6615
14        0   5667
15        0   3098
16        0   1521
17        1   9345
18        1   8488
19        1   6534
20        1   6302
21        1   6002
22        1   5814
23        1   5667
24        1   5454
25        1   3223
26        1   3124
27        1   1615
28        1   1521
29        2   9909
...     ...    ...
42464  1712   6745
42465  1712   6595
42466  1712   6409
42467  1712   6408
42468  1712   6385
42469  1712   6315
42470  1712   6182
42471  1712   5953
42472  1712   5940
42473  1712   5824
42474  1712   5717
42475  1712   5715
42476  1712   5399
42477  1712   5386
42478  1712   5380
42479  1712   4602
42480  1712   4526
42481  1712   4030
42482  1712   3947
42483  1712   3632
42484  1712   3513
42485  1712   3497
42486  1712   1555
42487  1712   1534
42488  1712   1533
42489  1712   1524
42490  1712   1423
42491  1712   1417
42492  1712   1404
42493  1712     60

[42494 rows x 2 columns]

In [50]:
# Series.to_dense

In [51]:
tfidf_array = tfidf.toarray()

In [52]:
print(tfidf_array)

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [53]:
newdf = pd.DataFrame(data=tfidf_array)

In [54]:
newdf.head()

0      1      2      3      4      5      6      7      8      9      ...  \
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  ...   

   10116  10117  10118  10119  10120  10121  10122  10123  10124  10125  
0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
1    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
2    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
3    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  
4    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0    0.0  

[5 rows x 10126 columns]

In [55]:
tfidf_array.shape

(1713, 10126)

In [56]:
newdf.shape

(1713, 10126)

In [57]:
newdf.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1713 entries, 0 to 1712
Columns: 10126 entries, 0 to 10125
dtypes: float64(10126)
memory usage: 132.3 MB


In [58]:
newdf[newdf[0] >0][0]

527     0.125524
1257    0.079642
Name: 0, dtype: float64

In [59]:
new_array= enumerate(tfidf_array)

In [60]:
print(tfidf_array.shape)

(1713, 10126)


In [61]:
for counter, doc in enumerate(tfidf_array):
    word_num = list(zip(bowxform.get_feature_names(), doc))
    one_doc_as_df = pd.DataFrame.from_records(word_num, columns=['term', 'score']).sort_values(by='score', ascending=False).reset_index(drop=True)

In [62]:
one_doc_as_df

term     score
0             drawings  0.498723
1              foreman  0.326147
2          US500977992  0.326147
3                jerry  0.317714
4                 loop  0.200994
5           electrical  0.160884
6                Randy  0.133996
7          engineering  0.133996
8                 Went  0.121356
9                    4  0.083436
10                work  0.078769
11            envolved  0.070695
12              000938  0.070695
13               Sabic  0.070695
14                Cody  0.070695
15              232653  0.070695
16            Compared  0.070695
17                NAVS  0.070695
18              225110  0.070695
19          purchasing  0.070695
20             package  0.070695
21             PVC4038  0.070695
22             PVC5038  0.070695
23                 PID  0.070695
24     SP1977310530206  0.070695
25                 KBR  0.070695
26              234018  0.070695
27            09242019  0.070695
28            08092019  0.070695
29             deleted  0.070695
...                ...       ...
10096           212224  0.000000
10097           212319  0.000000
10098           210950  0.000000
10099           212344  0.000000
10100           212351  0.000000
10101           212418  0.000000
10102           212451  0.000000
10103           212608  0.000000
10104           212616  0.000000
10105           212623  0.000000
10106           212028  0.000000
10107           211925  0.000000
10108           211914  0.000000
10109           211911  0.000000
10110           211025  0.000000
10111           211040  0.000000
10112           211052  0.000000
10113           211100  0.000000
10114           211132  0.000000
10115           211400  0.000000
10116           211434  0.000000
10117           211436  0.000000
10118           211542  0.000000
10119           211615  0.000000
10120           211723  0.000000
10121           211736  0.000000
10122           211740  0.000000
10123           211824  0.000000
10124           211855  0.000000
10125             “RC”  0.000000

[10126 rows x 2 columns]